# This image needs to be built with the workspace root as the build context.

ARG RUST_VERSION=1.92.0.0
ARG CHIP=esp32c3
ARG DISTRO_VERSION=3.23
ARG ESP_IDF_VERSION=5.3.3

ARG RUST_IMAGE=espressif/idf-rust:${CHIP}_${RUST_VERSION}
ARG RUNTIME_IMAGE=espressif/idf:v${ESP_IDF_VERSION}

FROM ${RUST_IMAGE} AS rust
RUN cargo install cargo-chef --locked
WORKDIR /app

# planner and builder in two different stages
# - recipe preparation depends on source code changes
# - recipe cooking depends on recipe changes

FROM rust AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM rust AS builder
ARG CARGO_TARGET_DIR=riscv32imc-esp-espidf
ARG CRATE_PATH
ARG BIN_NAME
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json
COPY . .
WORKDIR ${CRATE_PATH}
RUN --mount=type=cache,target=/app/target \
    cargo build --bins && \
    cp /app/target/${CARGO_TARGET_DIR}/debug/${BIN_NAME} /tmp/entrypoint

FROM ${RUNTIME_IMAGE} AS runtime
COPY --from=builder /tmp/entrypoint /usr/local/bin/entrypoint
ENTRYPOINT [ "/usr/local/bin/entrypoint" ]
