ARG RUST_VERSION=1.92.0
ARG DISTRO_NAME=alpine
ARG DISTRO_VERSION=3.23

ARG RUST_IMAGE=rust:${RUST_VERSION}-${DISTRO_NAME}${DISTRO_VERSION}
ARG RUNTIME_IMAGE=${DISTRO_NAME}:${DISTRO_VERSION}

FROM ${RUST_IMAGE} AS rust
RUN cargo install cargo-chef --locked
WORKDIR /app

# planner and builder in two different stages
# - recipe preparation depends on source code changes
# - recipe cooking depends on recipe changes

FROM rust AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM rust AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json
COPY . .
ARG CRATE_PATH
WORKDIR ${CRATE_PATH}
RUN cargo build --bins

FROM ${RUNTIME_IMAGE} AS runtime
ARG BIN_NAME
COPY --from=builder /app/target/debug/${BIN_NAME} /usr/local/bin/entrypoint
ENTRYPOINT [ "/usr/local/bin/entrypoint" ]
