[build]
target = "riscv32imc-esp-espidf"

# https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#rust-configuration-flags
[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md
MCU = "esp32c3"
